server:
    bind:
        host: 0.0.0.0
        port: 5001
    url: ${WDR_ELASTICSEARCH_URL}
    basepath: /
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-CA
    cors: true
    pretty_print: true
    limit: 500
    # templates: /path/to/templates
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: ERROR
    # logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Meteorological Service of Canada Geospatial Web Services
        description: The weather can have an incredible influence on our daily lives. It affects the growth of crops and the availability of water. It dictates which regions of the world are habitable or uninhabitable
        keywords:
            - Weather
            - Meteorology
            - Climate
            - Forecasting
            - Floods
            - Weather alerts
            - Storms
            - Wind
            - Temperature
            - Precipitation
            - Snow
            - Ice
        keywords_type: theme
        terms_of_service: https://www.canada.ca/en/transparency/terms.html
        url: https://www.canada.ca/en/services/environment/weather.html
    license:
        name: Environment and Climate Change Canada Data Server End-use Licence
        url: https://dd.weather.gc.ca/doc/LICENCE_GENERAL.txt
    provider:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        url: https://www.canada.ca/en/services/environment/weather.html
    contact:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        position: Service Channel
        address: 77 Westmorland Street, Suite 260
        city: Fredericton
        stateorprovince: New Brunswick
        postalcode: E3B 6Z3
        country: Canada
        phone: None
        fax: +01-506-451-6010
        email: ec.ecweather-meteo.ec@canada.ca
        url: https://weather.gc.ca/mainmenu/contact_us_e.html
        hours: Monday to Friday, 1300h - 2100h UTC
        instructions: During hours of service
        role: pointOfContact

datasets:
    projects:
        title: WOUDC Data Registry Projects
        description: Connection to projects in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.project
            id_field: identifier
            properties:
                - identifier
    datasets:
        title: WOUDC Data Registry Datasets
        description: Connection to datasets in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.dataset
            id_field: identifier
            properties:
                - identifier
    countries:
        title: WOUDC Data Registry Countries
        description: Connection to countries in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.country
            id_field: identifier
            properties:
                - identifier
                - country_name_en
                - country_name_fr
                - link
                - wmo_region_id
                - regional_involvement
                - wmo_membership
    contributors:
        title: WOUDC Data Registry Contributors
        description: Connection to contributors in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.contributor
            id_field: identifier
            properties:
                - identifier
                - name
                - url
                - country_code
                - wmo_region_id
                - active
                - email
                - ftp_username
                - last_validated_datetime
    stations:
        title: WOUDC Data Registry Stations
        description: Connection to stations in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARH_URL}/woudc_data_registry.station
            id_field: woudc_id
            properties:
                - woudc_id
                - gaw_id
                - type
                - name
                - country_code
                - wmo_region_id
                - active
                - last_validated_datetime
    instruments:
        title: WOUDC Data Registry Instruments
        description: Connection to instruments in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.instrument
            id_field: identifier
            properties:
                - identifier
                - dataset
                - station_id
                - name
                - model
                - serial
    deployments:
        title: WOUDC Data Registry Deployments
        description: Connection to contributor deployments in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.deployment
            id_field: identifier
            properties:
                - identifier
                - contributor
                - station_id
                - start_date
                - end_date
    data_records:
        title: WOUDC Data Registry Data Records
        description: Connection to data records in the WOUDC Data Registry Search Index.
        keywords: []
        links: []
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 1928-08-18
                end: null # or empty
        provider:
            name: Elasticsearch
            data: ${WDR_ELASTICSEARCH_URL}/woudc_data_registry.data_record
            id_field: identifier
            date_field: timestamp_date
            properties:
                - identifier
                - content_class
                - content_category
                - content_level
                - content_form
                - data_generation_date
                - data_generation_agency
                - data_generation_version
                - data_generation_scientific_authority
                - platform_type
                - platform_id
                - platform_name
                - platform_country
                - platform_gaw_id
                - instrument_name
                - instrument_model
                - instrument_number
                - timestamp_utcoffset
                - timestamp_date
                - timestamp_time
                - published
                - received_datetime
                - inserted_datetime
                - processed_datetime
                - published_datetime
                - number_of_observations
                - ingest_filepath
                - filename
                - output_filepath
                - url
